export enum orderActionTypes {
	ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST',
	ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS',
	ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL',

	ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST',
	ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS',
	ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL',

	ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST',
	ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS',
	ORDER_PAY_FAIL = 'ORDER_PAY_FAIL',
	ORDER_PAY_RESET = 'ORDER_PAY_RESET',

	ORDER_DELIVER_REQUEST = 'ORDER_DELIVER_REQUEST',
	ORDER_DELIVER_SUCCESS = 'ORDER_DELIVER_SUCCESS',
	ORDER_DELIVER_FAIL = 'ORDER_DELIVER_FAIL',
	ORDER_DELIVER_RESET = 'ORDER_DELIVER_RESET',

	ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST',
	ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS',
	ORDER_LIST_FAIL = 'ORDER_LIST_FAIL',
}

export enum userOrdersActionTypes {
	USER_ORDERS_REQUEST = 'USER_ORDERS_REQUEST',
	USER_ORDERS_SUCCESS = 'USER_ORDERS_SUCCESS',
	USER_ORDERS_FAIL = 'USER_ORDERS_FAIL',
	USER_ORDERS_RESET = 'USER_ORDERS_RESET',
}
